### ISSUE TITLE
recursiveCheckPricelist blowing stack

### ISSUE THREAD

**Issue by joekiller** [TF2Autobot/tf2autobot#1095]
I guess with big enough price lists, the recursion in the check pricelist is causing an exception. https://github.com/TF2Autobot/tf2autobot/blob/9fddc53823e762f7f1c859afa067005fcdc1b672/src/classes/Listings.ts#L299

![image](https://user-images.githubusercontent.com/1022919/166679856-f17e09fb-fd1c-4ca6-82ce-16014d5e4f7f.png)
![image](https://user-images.githubusercontent.com/1022919/166679917-417c2000-7f56-4e45-b71f-524abf4360e4.png)

```
Stack trace:
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at interpolate (C:\tf2autobot\node_modules\pluralize\pluralize.js:75:16)
    at C:\tf2autobot\node_modules\pluralize\pluralize.js:89:20
    at String.replace (<anonymous>)
    at replace (C:\tf2autobot\node_modules\pluralize\pluralize.js:88:17)
    at sanitizeWord (C:\tf2autobot\node_modules\pluralize\pluralize.js:119:38)
    at Function.plural (C:\tf2autobot\node_modules\pluralize\pluralize.js:149:14)
    at pluralize (C:\tf2autobot\node_modules\pluralize\pluralize.js:177:46)
    at Currencies.toString (C:\tf2autobot\node_modules\@tf2autobot\tf2-currencies\lib\currencies.js:60:18)
    at replaceDetails (C:\tf2autobot\dist\classes\Listings.js:384:38)
    at Listings.getDetails (C:\tf2autobot\dist\classes\Listings.js:400:23)
    at Listings.getDetails (C:\tf2autobot\dist\classes\Listings.js:440:37)
    at Listings.getDetails (C:\tf2autobot\dist\classes\Listings.js:440:37)
    at Listings.getDetails (C:\tf2autobot\dist\classes\Listings.js:440:37)
    at Listings.getDetails (C:\tf2autobot\dist\classes\Listings.js:440:37)
    at Listings.getDetails (C:\tf2autobot\dist\classes\Listings.js:440:37)
```

**Comment by idinium96** [comment]
Aiyoo

**Comment by joekiller** [comment]
Had to revert to 4.7.0

**Comment by idinium96** [comment]
For now, please edit your `details.buy` and `details.sell` to maybe only have one `%name%`, and total characters less than 150.

I think this is because the bot called `getDetails` method two times for each buy and sell order, because the generated details might be more than 200 characters.

v4.8.0 introduced such checking, and since v4.9.0, the archived listings are also counted, so yeah.

**Comment by joekiller** [comment]
Okay I'll give that a try

**Comment by idinium96** [comment]
any good news?

**Comment by idinium96** [comment]
You're welcome. It still needs some optimization. I will try to research it later.

**Comment by joekiller** [comment]
Yeah something like just slice the string if the length is too long and
blerp a warning

Sent via mobile

**Comment by idinium96** [comment]
Yeah, like that simplicity. I will consider it.
