### ISSUE TITLE
bot failing to start in cmd, "Failed to get descriptions"

### ISSUE THREAD

**Issue by cainagabrieel** [TF2Autobot/tf2autobot#1345]
Stack trace:
Error: Failed to get descriptions
    at C:\Users\mineb\Desktop\tf2autobot\node_modules\@tf2autobot\steamcommunity\components\users.js:547:12
    at SteamCommunity._checkHttpError (C:\Users\mineb\Desktop\tf2autobot\node_modules\@tf2autobot\steamcommunity\components\http.js:110:3)
    at Request._callback (C:\Users\mineb\Desktop\tf2autobot\node_modules\@tf2autobot\steamcommunity\components\http.js:50:61)
    at Request.self.callback (C:\Users\mineb\Desktop\tf2autobot\node_modules\request\request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (C:\Users\mineb\Desktop\tf2autobot\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:513:28)
    at Gunzip.<anonymous> (C:\Users\mineb\Desktop\tf2autobot\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at Gunzip.emit (node:events:513:28)
Bot has been up for 20 seconds.

**Comment by snkxyz** [comment]
This error comes from the steam fallback API, and just as all other steam API errors, there is nothing that can be done by the bot to resolve the issue, all you can do is wait until the fallback API becomes more stable. I managed to take a picture of the error while searching for an inventory through the fallback API in my browser: https://imgur.com/a/rUuGpBE

**Comment by garaiza-93** [comment]
If an error involves something from Steam API, nothing can be done. All you can do is wait for the issue to pass.
You can easily sniff this out by looking for "SteamCommunity" or "Steam" in your log.
This is not the bot's fault. Closing.
