### ISSUE TITLE
input.match is not a function

### ISSUE THREAD

**Issue by Slips-PC** [TF2Autobot/tf2autobot#1478]
**Describe the bug**
When trying to start the bot, I get an error `input.match` is not a function.

**To Reproduce**

1. Configure your ecosystem.json.
2. Start the bot using pm2.

**Expected behavior**
The bot starts normally.

**Screenshots and logs**
```
2023-01-19 22:52:30 [34mdebug[39m: Connecting to PM2...
2023-01-19 22:52:30 [32minfo[39m: Starting bot...
2023-01-19 22:52:30 [31merror[39m: TF2Autobot failed to start properly, this is most likely a temporary error. See the log:
package.version: 5.6.0; node: v16.19.0 linux x64}
Stack trace:
TypeError: input.match is not a function
    at new SteamID (/root/tf2autobot/node_modules/steamid/index.js:122:31)
    at /root/tf2autobot/dist/classes/Bot.js:121:96
    at Array.map (<anonymous>)
    at new Bot (/root/tf2autobot/dist/classes/Bot.js:121:81)
    at /root/tf2autobot/dist/classes/BotManager.js:58:32
    at /root/tf2autobot/dist/classes/BotManager.js:65:17
    at /root/tf2autobot/node_modules/async/dist/async.js:2588:44
    at replenish (/root/tf2autobot/node_modules/async/dist/async.js:446:21)
    at iterateeCallback (/root/tf2autobot/node_modules/async/dist/async.js:430:21)
    at /root/tf2autobot/node_modules/async/dist/async.js:327:20
    at tryCatcher (/root/tf2autobot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/root/tf2autobot/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/root/tf2autobot/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/root/tf2autobot/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/tf2autobot/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/tf2autobot/node_modules/bluebird/js/release/async.js:93:12)
Bot has been up for 2 seconds.
2023-01-19 22:52:30 [34mdebug[39m: Shutdown has been initialized, stopping... {"err":"uncaughtException"}
2023-01-19 22:52:30 [34mdebug[39m: Bot instance was not yet created
2023-01-19 22:52:30 [34mdebug[39m: Waiting for files to be saved
2023-01-19 22:52:30 [34mdebug[39m: Done waiting for files
2023-01-19 22:52:30 [33mwarn[39m: Exiting...
```
**Additional context**

Version:  v5.6.0

**Comment by Slips-PC** [comment]
Nevermind, I found the issue. I didn't have quotes surrounding my Steamid in the `ITEM_STATS_WHITELIST` var.
