### ISSUE TITLE
Sesion problems i guess

### ISSUE THREAD

**Issue by VoidDave** [TF2Autobot/tf2autobot#1543]
**Describe the bug**

**To Reproduce**

1. start bot

**Expected behavior**

**Screenshots and logs**
F:\SteamTradeBot\tf2autobot>node dist/app.js
2023-05-04 08:23:38 warn: You are not running the bot with PM2! If the bot crashes it won't start again. Get a VPS and run your bot with PM2: https://github.com/TF2Autobot/tf2autobot/wiki/Getting-a-VPS
2023-05-04 08:23:40 debug: Connecting to PM2...
2023-05-04 08:23:40 info: Starting bot...
2023-05-04 08:23:40 debug: Calling onRun
2023-05-04 08:23:40 debug: Setting poll data
2023-05-04 08:23:40 debug: Setting login attempts
2023-05-04 08:23:40 info: Signing in to Steam...
2023-05-04 08:23:40 debug: Starting login attempt
2023-05-04 08:23:41 error: Failed to sign in to Steam:  AccessDenied {"eresult":15}
2023-05-04 08:23:41 warn: Failed to sign in to Steam:  AccessDenied {"eresult":15}
2023-05-04 08:23:41 error: TF2Autobot failed to start properly, this is most likely a temporary error. See the log:
package.version: 5.7.0; node: v18.16.0 win32 x64}
Stack trace:
Error: AccessDenied
    at SteamUser._handleLogOnResponse (F:\SteamTradeBot\tf2autobot\node_modules\steam-user\components\09-logon.js:784:17)
    at SteamUser.<anonymous> (F:\SteamTradeBot\tf2autobot\node_modules\steam-user\components\09-logon.js:795:7)
    at F:\SteamTradeBot\tf2autobot\node_modules\steam-user\components\classes\HandlerManager.js:35:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (F:\SteamTradeBot\tf2autobot\node_modules\steam-user\components\classes\HandlerManager.js:34:12)
    at SteamUser._handleMessage (F:\SteamTradeBot\tf2autobot\node_modules\steam-user\components\03-messages.js:641:25)
    at SteamUser._handleNetMessage (F:\SteamTradeBot\tf2autobot\node_modules\steam-user\components\03-messages.js:562:8)    at SteamUser._processMulti (F:\SteamTradeBot\tf2autobot\node_modules\steam-user\components\03-messages.js:693:9) {
  eresult: 15
}
Bot has been up for 3 seconds.
2023-05-04 08:23:41 debug: Shutdown has been initialized, stopping... {"err":"uncaughtException"}
2023-05-04 08:23:41 debug: Disabling Autokeys and disabling key entry in the pricelist...
2023-05-04 08:23:41 debug: Handler finished cleaning up
2023-05-04 08:23:41 debug: Waiting for files to be saved
2023-05-04 08:23:41 debug: Done waiting for files
2023-05-04 08:23:41 warn: Exiting...
![image](https://user-images.githubusercontent.com/62336875/236126410-c3abaec3-6e55-4dfb-8766-7af0608427ca.png)

Version: 
5.7.0

**Comment by idinium96** [comment]
![image](https://user-images.githubusercontent.com/47635037/236289663-a44726c5-b091-4a37-8dab-8d20849f34ab.png)
<https://github.com/TF2Autobot/tf2autobot/wiki/Common-Errors#access-denied>

<https://github.com/TF2Autobot/tf2autobot/wiki/Before-you-start>

**Comment by VoidDave** [comment]
I have steam unlimited and tf premium. Bot worked for about 2 weaks without issues

**Comment by VoidDave** [comment]
Propably valve changed something in api i guess

**Comment by VoidDave** [comment]
Any updates ?

**Comment by carlosliam** [comment]
@VoidDave Please try stopping the bot, deleting the file at `tf2autobot/files/{account_name}/loginToken.json`, and starting again. Please close the issue if this works, or leave another reply if it doesn't.

Additionally, you will be able to receive quicker support for bot issues if you choose to join our Discord server here: https://discord.gg/4k5tmMkXjB

**Comment by arik123** [comment]
Closing as this issue has been inactive for a while, if you still have this issue, please reopen
