### ISSUE TITLE
Repeated crash on restart, error not handled properly to resume running & retry

### ISSUE THREAD

**Issue by Refloow** [TF2Autobot/tf2autobot#1738]
After running for few hours without issues, on restart, it won't work anymore. Something is not loading, and instead of bot handling it, and retrying, it seems to just crash.

I manually checked and everything is okay with the account, and trading. Main problem is this error seems to appear every time after some time of the application running, it does not crash the app than, i tried manually restarting now it throws this on the start auto closing/crashing the application each time on restart, for over an hour.

"failed to start properly, this is most likely a temporary error. logs:

Stack trace:
Error: EYldRefreshAppIfNecessary(440) failed with EResult 55
at C:\Users\D-2382847JNDK\Desktop\tf2autobot-5.11.1\node_modules@tf2autobot\steamcommunity\components\users.js:612:12
at SteamCommunity._checkHttpError (C:\Users\D-2382847JNDK\Desktop\tf2autobot-5.11.1\node_modules@tf2autobot\steamcommunity\components\http.js:110:3)
at Request._callback (C:\Users\D-2382847JNDK\Desktop\tf2autobot-5.11.1\node_modules@tf2autobot\steamcommunity\components\http.js:50:61)
at self.callback (C:\Users\D-2382847JNDK\Desktop\tf2autobot-5.11.1\node_modules\request\request.js:185:22)
at Request.emit (node:events:514:28)
at Request.emit (node:domain:488:12)
at Request.<anonymous> (C:\Users\D-2382847JNDK\Desktop\tf2autobot-5.11.1\node_modules\request\request.js:1154:10)
at Request.emit (node:events:514:28)
at Request.emit (node:domain:488:12)
at Gunzip.<anonymous> (C:\Users\D-2382847JNDK\Desktop\tf2autobot-5.11.1\node_modules\request\request.js:1076:12)
at Object.onceWrapper (node:events:628:28)
at Gunzip.emit (node:events:514:28)
at Gunzip.emit (node:domain:488:12)
at endReadableNT (node:internal/streams/readable:1589:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"

Version: package.version: 5.11.1; node: v20.10.0 win32 x64}

**Comment by excellproj** [comment]
This is a problem on the Valve server side
