### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by xosmin** [TF2Autobot/tf2autobot#882]
hello

i'm getting very often crashes with the 4.4.7 version:

  Bot crashed!
TF2Autobot crashed! Please create an issue with the following log:
package.version: 4.4.7; node: v14.16.1 win32 x64}
Stack trace:
TypeError: Cannot read property 'length' of null
at Object.default (C:\Users\MI51\Desktop\Autom\tf2autobot\node_modules\js-levenshtein\index.js:21:11)
at Object.getItemAndAmount (C:\Users\MI51\Desktop\Autom\tf2autobot\dist\classes\Commands\functions\utils.js:66:62)
at Commands.buyOrSellCommand (C:\Users\MI51\Desktop\Autom\tf2autobot\dist\classes\Commands\Commands.js:416:30)
at Commands.processMessage (C:\Users\MI51\Desktop\Autom\tf2autobot\dist\classes\Commands\Commands.js:144:18)
at MyHandler.onMessage (C:\Users\MI51\Desktop\Autom\tf2autobot\dist\classes\MyHandler\MyHandler.js:341:23)
at Bot.onMessage (C:\Users\MI51\Desktop\Autom\tf2autobot\dist\classes\Bot.js:604:22)
at Immediate.<anonymous> (C:\Users\MI51\Desktop\Autom\tf2autobot\dist\classes\Bot.js:148:21)
at processImmediate (internal/timers.js:461:21)
Bot has been up for 45 minutes.
Sat Sep 04 2021 14:55:40 GMT+0300 (Eastern European Summer Time) • v4.4.7

thanks

**Comment by idinium96** [comment]
Thanks for the report. I will look into this later.
