### ISSUE TITLE
Error: Invalid group SteamID64 ""

### ISSUE THREAD

**Issue by HoraceHorsecollar** [TF2Autobot/tf2autobot#904]
Hello. This morning I was using my trading bot and everything was working perfectly as normal. I also have PM2 installed in case the bot were to crash or something, but I am running it on my computer and not paying for another server. I accidentally ended up unplugging the power cable and my whole computer turned off. So I restarted my computer and tried running my bot again but I got an error, so I deleted everything, while saving all the important information. I reinstalled everything as instructed and configured everything correctly to my knowledge, but I ended up getting a different kind of error this time. Here it is:

package.version: 4.4.7; node: v14.18.0 win32 x64}
Stack trace:
Error: Invalid group SteamID64 ""
    at C:\Users\snowd\Desktop\tf2autobot\dist\classes\MyHandler\MyHandler.js:88:31
    at Array.forEach (<anonymous>)
    at MyHandler.get groups [as groups] (C:\Users\snowd\Desktop\tf2autobot\dist\classes\MyHandler\MyHandler.js:86:24)
    at MyHandler.checkGroupInvites (C:\Users\snowd\Desktop\tf2autobot\dist\classes\MyHandler\MyHandler.js:1801:14)
    at MyHandler.onReady (C:\Users\snowd\Desktop\tf2autobot\dist\classes\MyHandler\MyHandler.js:199:14)
    at C:\Users\snowd\Desktop\tf2autobot\dist\classes\Bot.js:381:30
    at wrapper (C:\Users\snowd\Desktop\tf2autobot\node_modules\async\dist\async.js:268:20)
    at replenish (C:\Users\snowd\Desktop\tf2autobot\node_modules\async\dist\async.js:435:29)
    at iterateeCallback (C:\Users\snowd\Desktop\tf2autobot\node_modules\async\dist\async.js:424:21)
    at C:\Users\snowd\Desktop\tf2autobot\node_modules\async\dist\async.js:321:20
    at tryCatcher (C:\Users\snowd\Desktop\tf2autobot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\snowd\Desktop\tf2autobot\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\snowd\Desktop\tf2autobot\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\snowd\Desktop\tf2autobot\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\snowd\Desktop\tf2autobot\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\snowd\Desktop\tf2autobot\node_modules\bluebird\js\release\async.js:93:12)

Please let me know how to fix this problem. I tried reading through the commonly asked issues suggested in the tutorial of the tf2autobot github but I couldn't find one that matched. I'm sure this might be an easy solution but please let me know how to fix it. I really enjoy using this bot and I would hate to see it die today. Also let me know if there is anything else I need to include in this post to help better. Thanks in advance.

**Comment by idinium96** [comment]
Hello @HoraceHorsecollar, it's been 22 days, sorry for the late reply.
You might miss `npm run build` step while installing the bot.

Please refer to the wiki. If you have any more problems, please join our [Discord server](https://discord.gg/4k5tmMkXjB) and ask in the #help channel.
