### ISSUE TITLE
Rep.tf profile verification fails

### ISSUE THREAD

**Issue by brysondev** [TF2Autobot/tf2autobot#951]
**Describe the bug**
Rep.tf checks always fail.

**To Reproduce**

Enable ban profile checking in the `options.json` file.
Change `bypass.bannedPeople.checkMptfBanned` to `true`

```json
"bannedPeople": {
    "allow": false,
    "checkMptfBanned": true
}
```

**Expected behavior**

Trade verifies the user and processes trades.

**Screenshots and logs**
```
2021-12-25 16:37:27 warn: Failed to obtain data from Rep.tf:  Forbidden {"statusCode":403,"body":"error code: 1005","attempts":1}
2021-12-25 16:37:27 warn: Failed to make offer
2021-12-25 16:37:27 error: Error: Forbidden
at Request.errorHandler (/home/brysondev/tf2autobot/node_modules/request-retry-dayjs/index.js:113:19)
at Request.retryStrategy (/home/brysondev/tf2autobot/node_modules/request-retry-dayjs/index.js:49:29)
at Request.<anonymous> (/home/brysondev/tf2autobot/node_modules/requestretry/index.js:142:48)
at Request.self.callback (/home/brysondev/tf2autobot/node_modules/request/request.js:185:22)
at Request.emit (node:events:390:28)
at Request.<anonymous> (/home/brysondev/tf2autobot/node_modules/request/request.js:1161:10)
at Request.emit (node:events:390:28)
at IncomingMessage.<anonymous> (/home/brysondev/tf2autobot/node_modules/request/request.js:1083:12)
at Object.onceWrapper (node:events:509:28)
at IncomingMessage.emit (node:events:402:35)
at endReadableNT (node:internal/streams/readable:1343:12)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
statusCode: 403,
body: 'error code: 1005',
attempts: 1
}
```

Version: 
4.5.1

**Comment by brysondev** [comment]
Yeah my bad, I thought this was some sort of issue on my end. After looking into this, apparently the owner of the VPS I am using to host the bot has been naughty and got blocked by rep.tf.

I'll contact the owner and see if I can get it resolved.
